### ISSUE TITLE
Build a web service

### ISSUE THREAD

**Issue by espadrine** [badges/gh-badges#12]
[Buckler](https://github.com/gittip/img.shields.io) is a service to download _PNG_ images of badges with any text and color.

We can do the same, with an _SVG_ output.

This bug is here to track progress. A few issues:
- [x] Buckler relies on a single color, and applies a gradient to it.
- [x] Buckler relies on data sent in the URL. What format should we use?
- [x] Buckler has an associated server running. What DNS name should we use?

**Comment by espadrine** [comment]
I would argue for using the same URL format, so I'll detail it here.

`http://example.com/<SUBJECT>-<STATUS>-<COLOR>.png`

Each field can use `_` instead of spaces and must use `--` instead of `-` and `__` instead of `_`.

**Comment by espadrine** [comment]
So, I have good news, and I have bad news.

I have successfully made [a branch](https://github.com/espadrine/gh-badges/tree/single-color) in which we only rely on a single color, and it looks like this.

Before:
![before](https://f.cloud.github.com/assets/100689/1839624/dc7e89a6-747f-11e3-82d7-41a65525e232.png)

Single color:
![after](https://f.cloud.github.com/assets/100689/1839626/e07a37e4-747f-11e3-8611-30448e942db3.png)

It looks great in Firefox.

Which leads me to this: it does not work on Chrome.
The issue is that Chrome [does not implement SVG2 colors](https://code.google.com/p/chromium/issues/detail?id=225863), and therefore I cannot make a gradient with transparent color stops.

**Comment by mathiasbynens** [comment]
Doesn’t work in Chromium → doesn’t work in Opera. Also, WebKit seems to have the same bug, so no Safari support either :(

**Comment by mathiasbynens** [comment]
Really nice work, @espadrine! I just wish browsers would get with the program already :P FWIW, [it](http://rawgithub.com/espadrine/gh-badges/single-color/sheet.html) worked fine in Opera 12 (pre-Blink).

**Comment by espadrine** [comment]
> FWIW, it worked fine in Opera 12 (pre-Blink).

Shocker :P

I published an [issue for it](https://code.google.com/p/chromium/issues/detail?id=331516).

**Comment by espadrine** [comment]
Update: using `stop-opacity` works, too. Merged. First bullet point down.

**Comment by espadrine** [comment]
Commit 08172c504 implements an automated server, much like Buckler. Second bullet point down.
