### ISSUE TITLE
Tracking Gemnasium’s adoption of these badges

### ISSUE THREAD

**Issue by mathiasbynens** [badges/gh-badges#19]
I’d like [Gemnasium](https://gemnasium.com/) to offer their badges as SVG using the format used in this project.

I think these are all the badges Gemnasium needs:

| Badge | Link to example SVG code |
| --- | :-: |
| ![dependencies out-of-date](http://b.adge.me/:dependencies-out--of--date-yellow.svg) | [`/:dependencies-out--of--date-yellow.svg`](http://b.adge.me/:dependencies-out--of--date-yellow.svg) |
| ![devDependencies out-of-date](http://b.adge.me/:devDependencies-out--of--date-yellow.svg) | [`/:devDependencies-out--of--date-yellow.svg`](http://b.adge.me/:devDependencies-out--of--date-yellow.svg) |
| ![dependencies up-to-date](http://b.adge.me/:dependencies-up--to--date-brightgreen.svg) | [`/:dependencies-up--to--date-brightgreen.svg`](http://b.adge.me/:dependencies-up--to--date-brightgreen.svg) |
| ![devDependencies up-to-date](http://b.adge.me/:devDependencies-up--to--date-brightgreen.svg) | [`/:devDependencies-up--to--date-brightgreen.svg`](http://b.adge.me/:devDependencies-up--to--date-brightgreen.svg) |
| ![dependencies update!](http://b.adge.me/:dependencies-update!-red.svg) | [`/:dependencies-update!-red.svg`](http://b.adge.me/:dependencies-update!-red.svg) |
| ![devDependencies update!](http://b.adge.me/:devDependencies-update!-red.svg) | [`/:devDependencies-update!-red.svg`](http://b.adge.me/:devDependencies-update!-red.svg) |
| ![dependencies unknown](http://b.adge.me/:dependencies-unknown-lightgrey.svg) | [`/:dependencies-unknown-lightgrey.svg`](http://b.adge.me/:dependencies-unknown-lightgrey.svg) |
| ![dependencies none](http://b.adge.me/:dependencies-none-brightgreen.svg) | [`/:dependencies-none-brightgreen.svg`](http://b.adge.me/:dependencies-none-brightgreen.svg) |

Since there’s no appropriate public repository to file this request, I’ll just send them a link to this issue instead.

**Comment by mathiasbynens** [comment]
Filed http://gemnasium.freshdesk.com/support/tickets/405. /cc @gemnasium

**Comment by espadrine** [comment]
I'd love to have a link to a ![update!](http://b.adge.me/:dependencies-update!-red.svg) project to make sure my assumptions are correct.

**Comment by espadrine** [comment]
We now have Gemnasium integration.

Related: [Gemnasium's reaction](https://twitter.com/gemnasiumapp/status/425297222365089792) on Twitter!

**Comment by mathiasbynens** [comment]
Apparently Gemnasium has switched to a new support system since my first report, so I’ve reported it again: http://support.gemnasium.com/forums/236528-general/suggestions/5518400-use-svg-for-badges-so-they-still-look-sharp-on-r Vote for it if you agree!

**Comment by mathiasbynens** [comment]
Good news! Gemnasium just added our `.svg` badges as an alternative to their old `.png` ones. Examples:

https://gemnasium.com/mathiasbynens/he.png 
https://gemnasium.com/mathiasbynens/he.svg

[I asked them](http://support.gemnasium.com/forums/236528-general/suggestions/5518400-use-svg-for-badges-so-they-still-look-sharp-on-r) to consider serving the SVG image for both URLs, i.e. even for `.png` requests. If not, everybody would have to edit their README files to update the badge URLs, and many people won’t, so they’d still get the old blurry badges…

**Comment by espadrine** [comment]
\o/ Congrats!

**Comment by mathiasbynens** [comment]
> I asked them to consider serving the SVG image for both URLs, i.e. even for `.png` requests.

And they now do just that! Woohoo!
