### ISSUE TITLE
Add build script that generates SVG badges based on template

### ISSUE THREAD

**Issue by mathiasbynens** [badges/gh-badges#2]
This repository will mainly host the template on which the SVG badges are used.

But we’ll want to create several badges with different settings:
- different texts
- different colors (build status: failed → red)

It would be cool if, whenever we make changes to the main template, the various badges can be updated just by running a build script.

I’m thinking: a JSON config file that contains settings for each badge (incl. width for each part of the badge as well as the name of the gradient/color combination that should be used). So, for each badge, there would be an entry like this:

``` json
{
  "text": [ "build", "passed" ],
  "widths": [ 77, 45 ],
  "colorscheme": "green"
}
```

Any other ideas?

**Comment by espadrine** [comment]
I modified your format a bit. The minimum required is the following:

``` js
"build-passed": {
  /* Textual information shown, in order. */
  "text": [ "build", "passed" ],
  /* Width of the first box, width of the second box. */
  "widths": [ 33, 44 ],
  /* Gradient of the background color of the second box. */
  "colorB": [ "#8f6", "#4c1", "#3b0", "#370" ]
}
```

**Comment by mathiasbynens** [comment]
I’d still prefer referring to a color scheme name rather than hardcoding the colors in the file, as color schemes are likely to be re-used with different text. Or am I missing something?

**Comment by espadrine** [comment]
Where would we define the color schemes? In a different file?

Are there two distinct badges with the same color scheme in the wild?

**Comment by mathiasbynens** [comment]
> Where would we define the color schemes? In a different file?

Yeah, or maybe in the same file in a separate property at the top? Something like:

``` js
{
  "color-schemes": { … },
  "badges": { … }
}
```

> Are there two distinct badges with the same color scheme in the wild?

Sure, e.g. https://github.com/mathiasbynens/he#readme has these (from two different services!):

> [![Build status](https://travis-ci.org/mathiasbynens/he.png?branch=master)](https://travis-ci.org/mathiasbynens/he) [![Dependency status](https://gemnasium.com/mathiasbynens/he.png)](https://gemnasium.com/mathiasbynens/he)

https://github.com/svg/svgo#svgo---- has:

> [![NPM version](https://badge.fury.io/js/svgo.png)](https://npmjs.org/package/svgo) [![Dependency Status](https://gemnasium.com/svg/svgo.png)](https://gemnasium.com/svg/svgo) [![Build Status](https://secure.travis-ci.org/svg/svgo.png)](https://travis-ci.org/svg/svgo) [![Coverage Status](https://coveralls.io/repos/svg/svgo/badge.png?branch=master)](https://coveralls.io/r/svg/svgo)

**Comment by espadrine** [comment]
Ironically, it uses a different gradient!
