### ISSUE TITLE
Specify the branch for service images.

### ISSUE THREAD

**Issue by jmalloc** [badges/gh-badges#24]
It would be awesome if the branch name could be specified for Coveralls and Travis images - assuming this isn't already possible? :)

**Comment by mathiasbynens** [comment]
More info: for Travis, the URL format looks like:

```
https://travis-ci.org/mathiasbynens/jsesc.png?branch=master
```

gh-badges doesn’t support this yet AFAICT but it’s definitely possible to add support for this. Wanna submit a patch? :)

**Comment by espadrine** [comment]
The current Travis URL is: `http://b.adge.me/travis/<USER/REPO>.svg`.

@jmalloc Tell me what you'd find nice. `http://b.adge.me/travis/<USER/REPO/BRANCH>.svg`, maybe?

**Comment by jmalloc** [comment]
For reference the Coveralls URL is much the same:

```
https://coveralls.io/repos/recoilphp/recoil/badge.png?branch=develop
```

I'll give a patch a go, sure :)

@espadrine I like your example yes! As a personal preference I like including the branch in the path rather than the query parameters.

**Comment by espadrine** [comment]
@jmalloc If you want to give it a go, I advise you to change line 11 in `server.js` so that what we take takes slashes into account, ie, `([^/]+)` instead of `(.*)` in the regexp.

**Comment by Krinkle** [comment]
Branch names can contain slashes though. Implementing it as a query parameter here, too, might not be a bad idea.

**Comment by espadrine** [comment]
@Krinkle I was thinking more like `([^/]+)/([^/]+)/(.+)`, as in, no slash in the name and repo, but you can have a slash in the branch name.

**Comment by espadrine** [comment]
Done with #25.
