### ISSUE TITLE
Not rendering in Github

### ISSUE THREAD

**Issue by pikesley** [badges/gh-badges#32]
Is it just me, or are the badges borked for anybody else when used directly in a Github README?

See [here](https://github.com/pikesley/badger/blob/master/README.md), a row of missing images. And yet [here](http://pikesley.github.io/badger/), we're fully badged-up.

Interestingly, when I get the badges from `b.adge.me`, it works fine in the README.

Oh, I notice the badges for this project are similarly broken.

:(

**Comment by mathiasbynens** [comment]
[GitHub’s Image Proxy feature™](https://github.com/blog/1766-proxying-user-images) broke this. See https://github.com/rvagg/nodei.co/issues/9 for some more background.

**Comment by pikesley** [comment]
:golfclap:

**Comment by alrra** [comment]
Related discussion: https://github.com/badges/shields/issues/112.

**Comment by espadrine** [comment]
GitHub's @atmos promised to fix this within days. Is there anything I can do in the meantime?

**Comment by Offirmo** [comment]
Oh. So that's temporary. I just switched to .png for now.

**Comment by espadrine** [comment]
@Offirmo I believe it is fixed now. Can you confirm?

**Comment by Offirmo** [comment]
@espadrine I confirm that svg badges are working now https://github.com/Offirmo/network-constants.js

**Comment by espadrine** [comment]
@Offirmo Thanks a lot!
