### ISSUE TITLE
Add support for Version Badge

### ISSUE THREAD

**Issue by LostCrew** [badges/gh-badges#40]
hello guys,

what about adding the support for the [Version Badge](http://badge.fury.io/)?
i find it quite useful. thanks.

**Comment by espadrine** [comment]
We have support for gem, npm, PyPI, Hackage and Packagist versions. Is there something I am missing?

**Comment by LostCrew** [comment]
@espadrine yes, that i am dumb. sorry for the silliness.

**Comment by espadrine** [comment]
Nothing's dumb to me. Should we make that ability more obvious?

**Comment by LostCrew** [comment]
i guess grouping them together under a specific category (project version) would be clearer and more immediate. what do you think?

**Comment by espadrine** [comment]
Hmm. The current scheme is `/<vendor>/v/<vendor-specific string>`. I can't really change that, since it's heavily used in the wild. Would you consider it clearer to have `/v/<vendor>/<vendor-specific string>`?

**Comment by LostCrew** [comment]
no, sorry, i was referring to the [presentation page](http://shields.io/). the _Supported Services_ section doesn't group them into main categories, that might have confused me. thoughts?

**Comment by espadrine** [comment]
I guess there are three parts, _downloads_, _version_, and _miscellaneous_. I'll try to give it more structure.

**Comment by LostCrew** [comment]
@espadrine nice, thank you for the support :+1:

**Comment by espadrine** [comment]
Done in f2de13e.
