### ISSUE TITLE
Align color scheme names with Buckler’s

### ISSUE THREAD

**Issue by mathiasbynens** [badges/gh-badges#8]
For clarity, we could reuse these colorscheme names: https://github.com/gittip/img.shields.io#valid-colours

**Comment by espadrine** [comment]
Should we use all those color values: https://github.com/gittip/img.shields.io/blob/6b9c9493932be8d3baaa7d53afb1c8996a81de26/png.go#L27?

They're actually not the same as the shields.io values. The shields.io color used in "build passing" (which is close to buckler's green) is different from the one used in buckler (bright green).

As a result, right now, the color used in "build passing" (~bright green) is not the same as the one used in "dependencies: none" (~green).

**Comment by espadrine** [comment]
We have all of Buckler's color values.
